# Change these first
owner: TheSL18 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: TheSL18

sites:
  - name: API Listas Negras Globalists
    url: $API_LISTAS_NEGRAS_GLOBALISTS
  - name: API Login Globalists
    url: $API_LOGIN_GLOBALISTS
  - name: API S3 Condor
    url: $API_S3_CONDOR
  - name: S3 Condor
    url: $S3_CONDOR_WEB
  - name: API S3 Draggane
    url: $API_S3_DRAGGANE
  - name: S3 Draggane
    url: $S3_DRAGGANE_WEB
  - name: Servicios Globalists
    url: $GLOBALISTS_WEB
  - name: CBSLN
    url: $CBSLN
  - name: CBSIP
    url: $CBSIP

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.condorbs.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/TheSL18/upptime/master/assets/condor.svg
  name: Status Condor Bussiness Solutions
  introTitle: "**CBS** uptime monitor and status page."
  faviconSvg: https://raw.githubusercontent.com/TheSL18/upptime/master/assets/condor.svg
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: Condor Bussiness Solutions
      href: https://condorbs.net
      # href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
#
i18n:
  activeIncidents: Incidentes activos
  allSystemsOperational: 🟩 Todos los sistemas funcionan correctamente
  degradedPerformance: 🟨 Rendimiento degradado
  completeOutage: 🟥 Falla masiva de los sistemas
  partialOutage: 🟧 Corte parcial
  incidentReport: Informe del incidente n.º $NUMBER →
  activeIncidentSummary: Abierto el $DATE con $POSTS publicaciones
  incidentTitle: Detalles del incidente $NUMBER
  incidentDetails: Detalles del incidente
  incidentFixed: Solucionado
  incidentOngoing: En curso
  incidentOpenedAt: Abierto el
  incidentClosedAt: Cerrado el
  incidentViewOnGitHub: Ver y suscribirse en GitHub
  incidentCommentSummary: Publicado el $DATE por $AUTHOR
  incidentBack: ← Volver a todos los incidentes
  pastIncidents: Incidentes pasados
  pastIncidentsResolved: Resuelto en $MINUTES minutos con $POSTS publicaciones
  liveStatus: Estado en vivo
  overallUptime: "Tiempo de actividad general: $UPTIME"
  overallUptimeTitle: Tiempo de actividad general
  averageResponseTime: "Tiempo de respuesta promedio: $TIMEms"
  averageResponseTimeTitle: Respuesta promedio
  sevelDayResponseTime: Tiempo de respuesta de 7 días
  responseTimeMs: Tiempo de respuesta (ms)
  up: 🟩 Activo
  down: 🟥 Inactivo
  degraded: 🟨 Degradado
  ms: ms
  loading: Cargando
  navGitHub: GitHub
  # footer: Esta página es [código abierto]($REPO), impulsada por [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Límite de tasa excedido
  rateLimitExceededIntro: Has excedido el número de solicitudes que puedes hacer en una hora, por lo que tendrás que esperar antes de volver a acceder a este sitio web. Alternativamente, puedes agregar un token de acceso personal de GitHub para seguir utilizando este sitio web.
  rateLimitExceededWhatDoesErrorMean: ¿Qué significa este error?
  rateLimitExceededErrorMeaning: Este sitio web utiliza la API de GitHub para acceder a datos en tiempo real sobre el estado de nuestros sitios web. Por defecto, GitHub permite 60 solicitudes por hora a cada dirección IP, las cuales has consumido.
  rateLimitExceededErrorHowCanFix: ¿Cómo puedo solucionarlo?
  rateLimitExceededErrorFix: Puedes esperar otra hora y el límite de tu dirección IP se restaurará. Alternativamente, puedes agregar tu token de acceso personal de GitHub, que te da 5000 solicitudes adicionales por hora.
  rateLimitExceededGeneratePAT: Aprende cómo generar un token de acceso personal
  rateLimitExceededHasSet: Tienes un token de acceso personal configurado.
  rateLimitExceededRemoveToken: Eliminar token
  rateLimitExceededGitHubPAT: Token de acceso personal de GitHub
  rateLimitExceededCopyPastePAT: Copia y pega tu token
  rateLimitExceededSaveToken: Guardar token
  errorTitle: Se produjo un error
  errorIntro: Se produjo un error al intentar obtener los detalles del estado más reciente.
  errorText: Puedes volver a intentarlo en unos minutos.
  errorHome: Ir a la página principal
  pastScheduledMaintenance: Mantenimiento programado anterior
  scheduledMaintenance: Mantenimiento programado
  scheduledMaintenanceSummaryStarted: Empezó el $DATE durante $DURATION minutos
  scheduledMaintenanceSummaryStarts: Empezará el $DATE durante $DURATION minutos
  startedAt: Empezó el
  startsAt: Empezará el
  duration: Duración
  durationMin: $DURATION minutos
  incidentCompleted: Completado
  incidentScheduled: Programado
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1y
  durationAll: todo
